services:
  database:
    image: postgres:16.3
    container_name: "zoe_shop_posgresql"
    restart: always
    environment:
      - POSTGRES_USER=eliphaz
      - POSTGRES_PASSWORD=supersecr3t
      - POSTGRES_DB=zoeshopdb
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
      - '5469:5432'

  pgadmin:
    container_name: "zoe_shop_pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@domain.com
        PGADMIN_DEFAULT_PASSWORD: secret
        #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: true
        PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - '8069:80'

volumes:
  postgres:
